### ISSUE TITLE
Web Admin Assignment

### ISSUE THREAD

**Issue by Shahraaz** [CPHub-NITC/chapter#16]
Current Web Admin must give members guidance on how to build and maintain the website. Things like:

- How to make a PR and how merging works
- Let members edit a few pages like
  - Members.html
  - Index.html
  
 Add more points needed for this role in the comments

**Comment by kartiks-21** [comment]
Regarding both things

- I will tell them the basics and all on Friday.
- I will give them a few trivial tasks like updating few events on the events page.
